name: Setup Python
author: suyiiyii
description: Setup Python

runs:
  using: composite
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true
