name: Trigger Release

on:
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ github.token }}


      - uses: ./.github/actions/setup-python
        name: Setup Python & uv

      - run: echo "TAG_NAME=v$(uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version)" >> $GITHUB_ENV


      - name: Push Tag
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git tag ${{ env.TAG_NAME }}
          git push --tags
