name: Trigger Release

on:
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: ./.github/actions/setup-python
        name: Setup Python & uv

      - name: Push Tag
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git tag v$(uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version)
          git push && git push --tags
